### ISSUE TITLE
Bug when using Bot in a telegram group

### ISSUE THREAD

**Issue by JohnnyFFM** [enoy19/burst-mining-pool-bot#1]
Hi! 

Love your bot! One little thing that can be improved:
I run the bot in a telegram group (3 guys sharing a mining rig) and noticed that when i type “/“ and click on a command proposal the bot doesnt recognize it. Reason is that in groups a command is directly send to the bot like this: /pending@CGBurstPPBot instead of just /pending. Would be cool if the bot would recognise this as well.

And one more question: since it looks like I‘m leaving POCC pools soon due to the scheduled fee increase, does the bot support other pools running goburstpool?

Tx, Johnny

**Comment by enoy19** [comment]
Hi Johnny,

thanks for your feedback! I tried to implement it but I ran into a problem with arguments not being recognised by the bot, that's why I left the feature out, because I thought there might be no demand (and because I am lazy :P). 

I will be adding this feature as soon as I can!

The bot can support any pool software, if it has an api or any way to scape miner details. 
I might scrape the [miner details](https://github.com/PoC-Consortium/goburstpool/blob/master/web/templates/minerTable.tmpl) of the goburstpool by calling the miner table and parsing the html.

Can you please provide me a link to a pool that is currently running goburstpool?

**Comment by JohnnyFFM** [comment]
Cool! Guess is just a quick scan for the "@" and cut everything left to it including the "@."
There is a list of all pools using this software in the licensefile [LICENSE.md](https://github.com/PoC-Consortium/goburstpool/blob/master/LICENSE.md). Guess your bot will work with all of them.

**Comment by enoy19** [comment]
I just realized that the PoCC pool is a goburstpool... 😅
The bot supports any goburstpool, if you get an html table as a response to [/miners](https://50-50-pool.burst.cryptoguru.org/miners). Just [configure](https://github.com/enoy19/burst-mining-pool-bot/wiki/Hosting-and-Configuration#currently-supported-pools) the "cryptoguru.allminers.url" property correctly.

**Comment by enoy19** [comment]
Added the group chat feature in 1.1.0

**Comment by enoy19** [comment]
The bot needs admin privileges in a group chat and only responds to commands if the @botname is trailing:
/donate@MyBot

When a command is triggered, the bot actively listens to any input it get's.
