### ISSUE TITLE
"Old style treshold"

### ISSUE THREAD

**Issue by smaus84** [enoy19/burst-mining-pool-bot#3]
In the actual version if summed up value of BURST reached the threshold value, you get a notification.

In prevoius version the threshold worked different. You only got a notification when the pool awarded you the threshold amount of BURST in one go.

Could you please bring back that old behaviour? Maybe configurable to chose which one you want.

**Comment by enoy19** [comment]
Thanks! I forgot about the behaviour in the old version. I'll make it configurable.

**Comment by enoy19** [comment]
I came up with 3 modes of threshold handling:
 * **accumulate**: The default mode right now (1.1.0). It adds all incrementations of your pending payment and notifies you when the amount is greater than your threshold
 * **single**: Notifications will be sent when a single pending payment increase is greater than your threshold (the mode @smaus84 requested)
 * **payout**: The bot only counts payouts (pending payment decreases). And then works like accumulate. Since the threshold of accumulate can be reached at any given time of your mining progress. This mode focuses on payouts.
